# Generated by Django 3.2.3 on 2021-07-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickFood', '0002_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count',
            name='num',
        ),
        migrations.AddField(
            model_name='count',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
