# Generated by Django 3.2.3 on 2021-07-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickFood', '0004_auto_20210701_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='view_count',
        ),
    ]
