# Generated by Django 3.2.3 on 2021-07-01 15:50

from django.db import migrations, models
import hitcount.models


class Migration(migrations.Migration):

    dependencies = [
        ('pickFood', '0006_remove_counts_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('published_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('content', models.TextField(blank=True)),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.DeleteModel(
            name='Counts',
        ),
    ]
