# Generated by Django 3.2.3 on 2021-07-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickFood', '0007_auto_20210702_0050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
